export default {
    CONNECTION_STATUS: "CONNECTION_STATUS",
    SET_LIVE_STATS: "SET_LIVE_STATS",
    SET_LIVE_STATS_SETTINGS: "SET_LIVE_STATS_SETTINGS",
    UPDATE_LIVE_STAT_SETTING: "UPDATE_LIVE_STAT_SETTING",
    SET_SETTINGS_MODAL: "SET_SETTINGS_MODAL",
    STATE_RESET: "STATE_RESET",
    SET_LOGOUT: "SET_LOGOUT",
    SET_SCROLLABLE_VALUE: "SET_SCROLLABLE_VALUE",
    SET_LAST_REFRESH: "SET_LAST_REFRESH",
    SET_ORDER: "SET_ORDER",
    SET_SLA: "SET_SLA"
};