export default {
    SET_DISPLAY_INSTRUCTIONS: "SET_DISPLAY_INSTRUCTIONS",
    SET_DOMAIN: "SET_DOMAIN",
    SET_USERNAME: "SET_USERNAME",
    SET_PASSWORD: "SET_PASSWORD",
    SET_USERNAME_ERROR: "SET_USERNAME_ERROR",
    SET_PASSWORD_ERROR: "SET_PASSWORD_ERROR",
    SET_LOGIN_LOADER: "SET_LOGIN_LOADER",
    SET_LOGIN_STATUS: "SET_LOGIN_STATUS",
    SET_ACCOUNT: "SET_ACCOUNT",
    SET_LOGIN_FORM: "SET_LOGIN_FORM",
    SET_WHATS_MY_DOMAIN: "SET_WHATS_MY_DOMAIN",
    SET_REMEMBER_ME: "SET_REMEMBER_ME",
    CONNECTION_STATUS: "CONNECTION_STATUS"
};