export default {
    CONNECTION_STATUS: "CONNECTION_STATUS",
    SET_AGENTS_LIST: "SET_AGENTS_LIST",
    SET_AGENTS_MODAL: "SET_AGENTS_MODAL",
    SET_CURRENT_AGENT: "SET_CURRENT_AGENT",
    SET_AGENT_LIVE_STATISTICS: "SET_AGENT_LIVE_STATISTICS",
    SET_AGENT_TOTAL_TIME_SPENT: "SET_AGENT_TOTAL_TIME_SPENT",
    SET_AGENTS_FILTER_MODAL: "SET_AGENTS_FILTER_MODAL",
    SET_AGENTS_FILTER: "SET_AGENTS_FILTER",
    STATE_RESET: "STATE_RESET",
    SET_LOGOUT: "SET_LOGOUT",
    SET_AGENT_TIMER: "SET_AGENT_TIMER",
    SET_ALL_AGENTS_LIST: "SET_ALL_AGENTS_LIST"    
};