export default {
    CONNECTION_STATUS: "CONNECTION_STATUS",
    SET_QUEUES_LIST: "SET_QUEUES_LIST",
    SET_QUEUES_MODAL: "SET_QUEUES_MODAL",
    SET_CURRENT_QUEUE: "SET_CURRENT_QUEUE",
    SET_CURRENT_CUSTOMER_WAITING: "SET_CURRENT_CUSTOMER_WAITING",
    SET_ASSIGNED_AND_AVAILABLE_AGENTS: "SET_ASSIGNED_AND_AVAILABLE_AGENTS",
    SET_TOTAL_CALLS_LANDED_IN_QUEUE: "SET_TOTAL_CALLS_LANDED_IN_QUEUE",
    SET_QUEUES_FILTER_MODAL: "SET_QUEUES_FILTER_MODAL",
    SET_QUEUES_FILTER: "SET_QUEUES_FILTER",
    SET_QUEUES_FILTER_LIST: "SET_QUEUES_FILTER_LIST",
    STATE_RESET: "STATE_RESET",
    SET_LOGOUT: "SET_LOGOUT",
};